service: images-analysis
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - rekognition:DetectLabels
          Resource: "*"
        - Effect: "Allow"
          Action:
            - translate:TranslateText
          Resource: "*"

functions:
  images-analysis:
    handler: index.main
    events:
      - http:
          path: analysis
          method: get
