org: matheuslira13
app: hello-sls
service: hello-sls
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events:
      - http:
          path: hello
          method: get
